version: "3.8"
services:
  home-assistant:
    image: docker.io/homeassistant/home-assistant:stable
    mem_limit: 1024m
    container_name: rusnas-home-assistant
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Moscow
    volumes:
      - {{DATA_DIR:-/mnt/data/containers/home-assistant}}/config:/config
