#!/bin/bash
# rusNAS: Configure nginx as primary web server, move Apache to :8091 (WebDAV only)
# See: webservice.md for full architecture description
set -e

VM="rusnas@10.10.10.72"
PASS="kl4389qd"
SSH="sshpass -p '$PASS' ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no"
SCP="sshpass -p '$PASS' scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no"

echo "=== rusNAS: nginx primary web server setup ==="

# Step 1: Install nginx
echo "[1/8] Installing nginx..."
eval "$SSH $VM" 'sudo apt-get install -y nginx'

# Step 2: Create nginx rusnas apps directory
echo "[2/8] Creating /etc/nginx/conf.d/rusnas-apps/..."
eval "$SSH $VM" 'sudo mkdir -p /etc/nginx/conf.d/rusnas-apps'

# Step 3: Write main nginx site config
echo "[3/8] Writing nginx site config..."
eval "$SSH $VM" 'sudo tee /etc/nginx/sites-available/rusnas.conf > /dev/null' << 'NGINXCONF'
# rusNAS primary nginx config — see webservice.md
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    # Landing page (статика)
    root /var/www/rusnas-landing;
    index index.html;

    # Cockpit (WebSocket support required)
    location /cockpit/ {
        proxy_pass http://127.0.0.1:9090/cockpit/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 86400s;
    }

    # FileBrowser
    location /files/ {
        proxy_pass http://127.0.0.1:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size 4G;
    }

    # WebDAV (Apache backend on :8091)
    location /webdav/ {
        proxy_pass http://127.0.0.1:8091/webdav/;
        proxy_set_header Host $host;
        proxy_set_header Destination $http_destination;
        proxy_pass_header Authorization;
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 4G;
        proxy_request_buffering off;
    }

    # Container apps (auto-generated by Container Manager)
    include /etc/nginx/conf.d/rusnas-apps/*.conf;

    # Default: serve landing page
    location / {
        try_files $uri $uri/ /index.html;
    }
}
NGINXCONF

# Step 4: Enable site, disable default
echo "[4/8] Enabling nginx site..."
eval "$SSH $VM" '
    sudo ln -sf /etc/nginx/sites-available/rusnas.conf /etc/nginx/sites-enabled/rusnas.conf
    sudo rm -f /etc/nginx/sites-enabled/default
'

# Step 5: Migrate Apache to :8091 (WebDAV only)
echo "[5/8] Migrating Apache to internal port :8091..."
eval "$SSH $VM" '
    # Check if Apache WebDAV config exists
    if [ -f /etc/apache2/sites-enabled/webdav.conf ]; then
        # Update Listen directive to 8091 and bind to localhost only
        sudo sed -i "s/^Listen 80$/Listen 127.0.0.1:8091/" /etc/apache2/ports.conf 2>/dev/null || true
        sudo sed -i "s/<VirtualHost \*:80>/<VirtualHost 127.0.0.1:8091>/" /etc/apache2/sites-available/webdav.conf 2>/dev/null || true
        sudo sed -i "s/<VirtualHost \*:80>/<VirtualHost 127.0.0.1:8091>/" /etc/apache2/sites-enabled/webdav.conf 2>/dev/null || true
        # Remove default Apache site so it does not conflict
        sudo a2dissite 000-default.conf 2>/dev/null || true
        sudo systemctl restart apache2
        echo "Apache migrated to :8091"
    else
        echo "No WebDAV config found — Apache not reconfigured"
    fi
'

# Step 6: Update sudoers for nginx
echo "[6/8] Updating sudoers for nginx..."
eval "$SSH $VM" 'sudo tee /etc/sudoers.d/rusnas-nginx > /dev/null' << 'SUDOCONF'
# rusNAS: nginx management (see webservice.md)
rusnas ALL=(ALL) NOPASSWD: /usr/sbin/nginx -t
rusnas ALL=(ALL) NOPASSWD: /bin/systemctl reload nginx
rusnas ALL=(ALL) NOPASSWD: /bin/systemctl restart nginx
SUDOCONF

# Step 7: Test nginx config and start
echo "[7/8] Testing nginx config..."
eval "$SSH $VM" '
    sudo nginx -t && sudo systemctl enable nginx && sudo systemctl restart nginx
'

# Step 8: Verify services
echo "[8/8] Verifying services..."
eval "$SSH $VM" '
    echo "--- nginx status ---"
    sudo systemctl is-active nginx && echo "nginx: OK" || echo "nginx: FAILED"
    echo "--- listening ports ---"
    ss -tlnp | grep -E ":80|:8080|:8091|:9090" || true
'

echo ""
echo "=== nginx primary setup complete ==="
echo "Web services:"
echo "  Landing:     http://10.10.10.72/"
echo "  Cockpit:     http://10.10.10.72/cockpit/"
echo "  FileBrowser: http://10.10.10.72/files/"
echo "  WebDAV:      http://10.10.10.72/webdav/"
echo "  Container apps: http://10.10.10.72/<app_path>/"
echo ""
echo "See webservice.md for full architecture details."
