services:
  rocketchat:
    image: docker.io/library/rocket.chat:latest
    mem_limit: 2048m
    container_name: rusnas-rocketchat
    restart: unless-stopped
    depends_on:
      - rocketchat-mongo
    network_mode: host
    environment:
      - MONGO_URL=mongodb://localhost:27017/rocketchat?directConnection=true
      - MONGO_OPLOG_URL=mongodb://localhost:27017/local?directConnection=true
      - ROOT_URL={{ROOT_URL:-http://localhost:3000}}
      - PORT={{WEB_PORT:-3000}}
    volumes:
      - {{DATA_DIR:-/mnt/data/containers/rocketchat}}/uploads:/app/uploads

  rocketchat-mongo:
    image: docker.io/library/mongo:8
    container_name: rusnas-rocketchat-mongo
    restart: unless-stopped
    network_mode: host
    command: mongod --oplogSize 128 --replSet rs0 --bind_ip_all
    volumes:
      - {{DATA_DIR:-/mnt/data/containers/rocketchat}}/mongodb:/data/db
